### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by cabol** [cabol/cross_db#1]
## General Items

- [x] It has a github repo
- [x] It has a proper MIT LICENSE file
- [ ] It's has a clear and useful README.md
- [ ] It's documented using `edoc` (with examples)
- [x] It's tested
- [ ] it has 100% of coverage

## Features for First Version

- [x] Basic repo functions: `insert`, `update`, `delete`, `get`, `get_by` and `all`
- [ ] Complementary repo functions: `insert_all`, `update_all` and `delete_all`
- [x] Mnesia adapter – implement basic repo functions
- [ ] Mnesia adapter – implement complementary repo functions

## Exhibition

- [ ] There is a blog post about it
- [ ] It's shared on social networks
- [ ] It's shared on reddit
- [ ] It's shared on hacker news with a title like Show HN: description

## Examples

- [ ] It provides a sample application
- [x] Examples of use are documented in the README or linked from there

## Publish

- [ ] It's published on [Hex.pm](https://hex.pm)
